# Generated by Django 4.2.2 on 2023-06-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='yoouridea',
            field=models.IntegerField(null=True),
        ),
    ]
